// The two libraries are one design. This library's point-mass model must reproduce
// ballistics-pointmass to integration noise, or putting the model behind a seam changed the
// physics, which is the thing to fix rather than to tolerate.
//
// The libraries live in separate repositories, so the comparison travels as a recorded file
// generated by ballistics-pointmass/tools/dump_reference.cpp, the same way a recorded reference file does. Regenerate it only if that library's physics changes.

#include "ballistics/mm/ballistics.h"

#include "test_support.h"

#include <fstream>
#include <set>
#include <sstream>

using namespace Ballistics::MM;

namespace {

struct Row {
    std::string id;
    double elevationDeg = 0.0;
    double range = 0.0;
    double tof = 0.0;
    double crossrange = 0.0;
    double terminalSpeed = 0.0;
    double impactAngleDeg = 0.0;
    bool reachedGround = false;
};

std::vector<Row> readReference(const char* path) {
    std::vector<Row> rows;
    std::ifstream in(path);
    std::string line;

    while (std::getline(in, line)) {
        if (line.empty() || line[0] == '#' || line.rfind("id,", 0) == 0) {
            continue;
        }
        std::istringstream ss(line);
        Row r;
        std::string field;

        std::getline(ss, r.id, ',');
        std::getline(ss, field, ','); r.elevationDeg = std::stod(field);

        std::getline(ss, field, ',');
        if (field.empty()) {
            rows.push_back(r);
            continue;
        }
        r.range = std::stod(field);
        r.reachedGround = true;
        std::getline(ss, field, ','); r.tof = std::stod(field);
        std::getline(ss, field, ','); r.crossrange = std::stod(field);
        std::getline(ss, field, ','); r.terminalSpeed = std::stod(field);
        std::getline(ss, field, ','); r.impactAngleDeg = std::stod(field);
        rows.push_back(r);
    }
    return rows;
}

} // namespace

int main(int argc, char** argv) {
    if (argc < 2) {
        std::printf("usage: mm_test_crosslibrary <pointmass-reference.csv>\n");
        return 2;
    }

    const std::vector<Row> rows = readReference(argv[1]);
    CHECK_MSG(rows.size() == 36, "rows " + std::to_string(rows.size()));
    if (rows.empty()) {
        return test::summary("crosslibrary");
    }

    std::set<std::string> ids;
    for (const Row& row : rows) {
        ids.insert(row.id);
    }
    CHECK(ids.size() == 9);

    const Catalogue catalogue = Catalogue::withBuiltins();

    // Every round in the reference must exist here under the same id: the two catalogues are
    // generated from the same rounds.csv.
    CHECK(catalogue.size() == ids.size());

    Environment env = Environment::standard();
    env.latitude = 50.0;

    double worstRange = 0.0;
    double worstTof = 0.0;
    std::string worstCase;
    int compared = 0;

    for (const Row& row : rows) {
        const Projectile* p = catalogue.find(row.id);
        CHECK_MSG(p != nullptr, "not in this catalogue: " + row.id);
        if (p == nullptr) {
            continue;
        }

        const Result<Impact> got = predictImpact(
            ModelKind::PointMass,
            fromGround(p->muzzle.speed, glm::radians(row.elevationDeg), 0.0, 0.0), *p, env,
            GroundReference{0.0}, SolverConfig::precise());

        const std::string where = row.id + " at " + std::to_string(row.elevationDeg) + " deg";

        // Agreement includes agreeing that a shot does not come down.
        CHECK_MSG(static_cast<bool>(got) == row.reachedGround, where + ": " +
                                                                   describe(got.status));
        if (!got || !row.reachedGround) {
            continue;
        }

        ++compared;
        const double rangeError = std::abs(got->range - row.range) / row.range;
        const double tofError = std::abs(got->tof - row.tof) / row.tof;

        if (rangeError > worstRange) {
            worstRange = rangeError;
            worstCase = where;
        }
        worstTof = std::max(worstTof, tofError);

        CHECK_MSG(rangeError < 1e-9,
                  where + " range " + test::values(got->range, row.range, row.range * 1e-9));
        CHECK_MSG(tofError < 1e-9,
                  where + " tof " + test::values(got->tof, row.tof, row.tof * 1e-9));
        CHECK_NEAR(got->crossrange, row.crossrange, 1e-6);
        CHECK_REL(got->terminalSpeed, row.terminalSpeed, 1e-9);
        CHECK_NEAR(glm::degrees(got->impactAngle), row.impactAngleDeg, 1e-7);
    }

    std::printf("%d cases against ballistics-pointmass; worst range deviation %.3e (%s), "
                "worst tof %.3e\n",
                compared, worstRange, worstCase.c_str(), worstTof);

    return test::summary("crosslibrary");
}
